# Generated by Django 4.2 on 2025-05-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_caso_bizagi', models.CharField(help_text='Código único del caso en Bizagi.', max_length=255, unique=True)),
                ('num_prestamo', models.CharField(blank=True, help_text='Número de préstamo asociado al caso.', max_length=255, null=True)),
                ('docsoldv', models.TextField(blank=True, help_text='Documentos solicitados o validados.', null=True)),
                ('tipo_de_cuenta', models.CharField(blank=True, help_text='Tipo de cuenta (ahorros, corriente, etc.).', max_length=100, null=True)),
                ('numcta_debito', models.CharField(blank=True, help_text='Número de cuenta para débito.', max_length=255, null=True)),
                ('secuencia_cta', models.CharField(blank=True, help_text='Secuencia de la cuenta.', max_length=100, null=True)),
                ('codigo_del_banco', models.CharField(blank=True, help_text='Código del banco.', max_length=100, null=True)),
                ('codigo_ciudad', models.CharField(blank=True, help_text='Código de la ciudad.', max_length=100, null=True)),
                ('estado', models.CharField(default='PENDIENTE', help_text='Estado actual del caso (PENDIENTE, EN_PROCESO, RESUELTO, ERROR).', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el caso.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del caso.')),
                ('fecha_inicio_proceso', models.DateTimeField(blank=True, help_text='Fecha y hora en que se inició el procesamiento del caso.', null=True)),
                ('fecha_fin_proceso', models.DateTimeField(blank=True, help_text='Fecha y hora en que finalizó el procesamiento del caso.', null=True)),
                ('proceso_creador', models.CharField(blank=True, help_text='Identificador del script Python que creó el caso.', max_length=255, null=True)),
                ('proceso_actualizador', models.CharField(blank=True, help_text='Identificador del script Python que actualizó el caso por última vez.', max_length=255, null=True)),
                ('intentos_procesamiento', models.IntegerField(default=0, help_text='Número de veces que se ha intentado procesar el caso.')),
                ('ultimo_error', models.TextField(blank=True, help_text='Mensaje del último error ocurrido durante el procesamiento.', null=True)),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Campo para almacenar información adicional en formato JSON.', null=True)),
            ],
            options={
                'verbose_name': 'Caso Pendiente',
                'verbose_name_plural': 'Casos Pendientes',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
