# Generated by Django 5.2.2 on 2025-06-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casodebito',
            name='docsoldv',
            field=models.CharField(blank=True, help_text='Documentos solicitados o validados.', max_length=255, null=True),
        ),
    ]
