# Generated by Django 5.2.2 on 2025-06-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adagio', '0002_alter_casodebito_docsoldv'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodebito',
            name='doctitulardv',
            field=models.CharField(blank=True, help_text='Número de identificación del titular de la cuenta.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casodebito',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('GRABADO', 'GRABADO'), ('PENDIENTE BIZAGI', 'PENDIENTE BIZAGI'), ('FINALIZADO', 'FINALIZADO'), ('CON ERROR', 'CON ERROR')], default='PENDIENTE', help_text='Estado actual del caso.', max_length=100),
        ),
    ]
