# Generated by Django 5.2.2 on 2025-06-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adagio', '0003_casodebito_doctitulardv_alter_casodebito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodebito',
            name='tipo_debito',
            field=models.CharField(choices=[('AL TITULAR', 'AL TITULAR'), ('A TERCEROS', 'A TERCEROS')], default='AL TITULAR', help_text='Tipo de débito.', max_length=100),
        ),
    ]
