# Generated by Django 5.0.6 on 2025-06-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adagio', '0004_casodebito_tipo_debito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casodebito',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('GRABADO', 'GRABADO'), ('PENDIENTE BIZAGI', 'PENDIENTE BIZAGI'), ('FINALIZADO', 'FINALIZADO'), ('VALIDAR', 'VALIDAR'), ('CON ERROR', 'CON ERROR')], default='PENDIENTE', help_text='Estado actual del caso.', max_length=100),
        ),
    ]
