# Generated by Django 5.0.6 on 2025-06-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adagio', '0005_alter_casodebito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodebito',
            name='autoriza',
            field=models.CharField(blank=True, help_text='Indica quién autoriza el débito.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='casodebito',
            name='fecha_desembolso',
            field=models.CharField(blank=True, help_text='Fecha en la que se realizó el desembolso.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='casodebito',
            name='tipo_debito',
            field=models.CharField(choices=[('AL TITULAR', 'AL TITULAR'), ('A TERCEROS', 'A TERCEROS'), ('NO APLICA', 'NO APLICA')], default='AL TITULAR', help_text='Tipo de débito.', max_length=100),
        ),
    ]
