# Generated by Django 5.0.6 on 2025-06-18 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('MINUTOS', 'Cada X Minutos'), ('HORAS', 'Cada X Horas'), ('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('UNA_VEZ', 'Una Sola Vez')], default='DIARIO', max_length=10)),
                ('intervalo', models.PositiveIntegerField(blank=True, help_text="Ej: 15 (para 'Cada 15 Minutos')", null=True)),
                ('hora_ejecucion', models.TimeField(blank=True, help_text='La hora en que se debe ejecutar la tarea.', null=True)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], help_text='El día de la semana para ejecuciones semanales.', null=True)),
                ('dia_mes', models.IntegerField(blank=True, help_text='El día del mes (1-31) para ejecuciones mensuales.', null=True)),
                ('fecha_ejecucion_unica', models.DateTimeField(blank=True, help_text='La fecha y hora para una ejecución única.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmarque para desactivar esta tarea sin eliminarla.')),
                ('id_tarea_django_q', models.CharField(blank=True, editable=False, max_length=100)),
                ('process', models.ForeignKey(help_text='El proceso que se ejecutará.', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='automations.automatedprocess')),
            ],
            options={
                'verbose_name': 'Tarea Programada',
                'verbose_name_plural': 'Tareas Programadas',
                'ordering': ['process__name'],
            },
        ),
    ]
