# Generated by Django 5.0.6 on 2025-07-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Hora de fin del rango permitido para ejecución (solo para tareas por minutos/horas).', null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio del rango permitido para ejecución (solo para tareas por minutos/horas).', null=True),
        ),
    ]
